### ISSUE TITLE
Feature Request: Hooks to add additional columns to Approvals table.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-approvals#59]
A support user has requested the ability to add new columns to the Approvals table.

https://github.com/strangerstudios/pmpro-approvals/blob/e1eea7cfd9e69309dccdd04bb8caa3c54f812779/adminpages/approvals.php#L120-L209

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/how-to-customize-pmpro-add-ons/

**Comment by andrewlimaza** [comment]
I think that'll be good. We could copy code from core:

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/adminpages/memberslist.php#L169

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/adminpages/memberslist.php#L230

**Comment by andrewlimaza** [comment]
Fixed in https://github.com/strangerstudios/pmpro-approvals/pull/78

**Comment by kblizeck** [comment]
Reposting here just in case: 
@andrewlimaza Is there anyway to request that the data passed to the pmpro_approvals_list_extra_cols_body hook is the single user that is for that row? Right now, you're passing all $theusers data, so there's not distinguishing what row I'm currently on in order to display additional meta data about that specific user.

**Comment by andrewlimaza** [comment]
Thanks for the feedback, please can you open an issue on Github and we'll get it patched as soon as we can (or feel free to submit a PR to solve this).

**Comment by andrewlimaza** [comment]
I just merged in one pull request that fixes the one issue I believe. We will be working on the other part of this shortly. - https://github.com/strangerstudios/pmpro-approvals/pull/120
